### ISSUE TITLE
Keplr Wallet Issues

### ISSUE THREAD

**Issue by cage17wlc** [chainapsis/keplr-extension#62]
Yesterday, 2/25/21, I sent 135.999 ATOM to the keplr wallet. I have a successful confirmation for this transaction in Trust Wallet and on MINTSCAN. Keplr is only showing 48.70021 ATOM in my available balance. Please correct this issue.

Thank You,
Camille

**Comment by dogemos** [comment]
Hi @cage17wlc, we've identified an issue where one of the Cosmos Hub nodes we connect with is failing to sync with the latest block. Working with our node provider to resolve this issue ASAP.

**Comment by cage17wlc** [comment]
Thank you for your response. Please let me know once it has been resolved.

**Comment by dogemos** [comment]
Hi @cage17wlc, the issue should be mostly resolved now. Could you check and let me know if you happen to run into the same issues?

**Comment by cage17wlc** [comment]
Hello, unfortunately I am still seeing the same error.

Thank You,
Camille

**Comment by hww824** [comment]
After clearing the Google cache, I lost my wallet. When I use the mnemonic phrase to restore my wallet, it always prompts me that the mnemonic phrase is invalid. I am very confused. What should I do?

**Comment by hww824** [comment]
I restored my wallet and a word is missing from the mnemonic. But maybe because of too many attempts, it shows that my key is locked or not initialized. what can I do?

**Comment by dogemos** [comment]
Please reach out to us on our Telegram support channel [here](https://t.me/keplrwallet). Happy to help troubleshoot in a more timely manner there!
